name: Test CodeAuditor Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      issues: write
    steps:
      - uses: actions/checkout@v3
      - name: CodeAuditor Workflow
        uses: SSWConsulting/codeauditor-scan-site@1.0.0
        with:
          # Your CodeAuditor token
          token: ${{ secrets.CODEAUDITORTOKEN }}
          # Your Scan URL
          url: ${{ vars.SCANURL }}
          # Your GitHub Token
          GitHub_Token: ${{ github.token }}
